#!/bin/bash

cd $OPENSHIFT_REPO_DIR

java -jar target/shoppinglist-server-*.jar db migrate openshift.yml
nohup java -jar target/shoppinglist-server-*.jar server openshift.yml 2>&1 > $OPENSHIFT_DATA_DIR/start.`date +"%Y-%m-%d-%I.%M.%S"`.log &

