language: java
before_install:
- npm install -g gulp
- gem install compass
jdk:
- oraclejdk7
- oraclejdk8
- openjdk7
after_success:
- git config user.name '$GIT_NAME'
- git config user.email '$GIT_EMAIL'
- git commit -a -m "Added deployment archive for Travis-CI build number $TRAVIS_JOB_ID"
deploy:
  provider: openshift
  user: m.th.mulders@xs4all.nl
  password:
    secure: FaPmkFwtL8+DTrvG/TqVYJ/TdXIWQXf45m7hU0kcgPFeX5Fz4ATRzrsFAh9QaQ96xqsnVdnXAqBWUnBFPCmnh8By+n2IxiC9SqgDPQ4WZaCO4W0EajcHX2PBhRPkXE2y/+0gMTlN3alqQpEBrRvaCeWPlsMMOnSk/Gbo57bKIBQ=
  app: shopping2
  domain: mulders
  on:
    repo: mthmulders/shoppinglist
    jdk: openjdk7
env:
  global:
    secure: SK5WpF7KYF5D+argH6krYnsb5GVv2FvNryKI1ZJpZ6CbNhbcPcjicsBWVMao9nK9ccGTsAFig2TfeMLS1+bVMM4E4XW/SPFsx3HAJp23ErMHBn5tm0EqJIxKFb8GflDadM2noBq7//h/Ldu+8mP2OvFKvVslTHSUODFGjq4PKTU=
